
- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - homebrew/cask
    homebrew_packages:
      - name: git
      - name: vim
      - name: wget
      - name: fish
      - name: tree
      - name: pipenv
      - name: imagemagick
      - name: anyenv
      - name: trash
      - name: neovim
      - name: deno
      - name: java
      - name: clojure/tools/clojure
      - name: rust
      - name: jq
      - name: z
      - name: peco
    homebrew_cask_packages:
      # ブラウザ
      - name: google-chrome
      - name: firefox
      # エディタ
      - name: visual-studio-code
      # 開発環境
      - name: android-studio
      - name: chromedriver
      - name: docker
      - name: unity-hub
      - name: blender
      - name: processing
      - name: mamp
      - name: responsively
      - name: ngrok/ngrok/ngrok
      - name: flutter
      # 配信
      - name: obs
      - name: obs-virtualcam
      # コミュニケーション
      - name: zoom
      - name: messenger
      - name: slack
      - name: webex
      - name: discord
      # 常駐ツール
      - name: gyazo
      - name: notion
      - name: google-drive
      - name: todoist
      - name: deepl
      - name: toggl-track
      - name: grammarly
      # Office系ツール
      - name: chrome-remote-desktop-host
      # クリエイティブ系
      # ツール
      - name: vlc

  tasks:
    ##########
    # Homebrew
    ##########
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    ####################
    # Download dotfiles
    ####################
    - name: git clone dotfiles
      ansible.builtin.git:
        repo: git@github.com:shinyaoguri/dotfiles.git
        dest: '{{ ansible_env.HOME }}/dotfiles'
    
    - name: fish-shell config symlinks
      file:
        src: '{{ ansible_env.HOME}}/dotfiles/config.fish'
        dest: '{{ ansible_env.HOME}}/.config/fish/config.fish'
        state: link
        force: yes

    - name: neovim .config/nvim mkdir
      file:
        path: '{{ ansible_env.HOME }}/.config/nvim'
        state: directory

    - name: neovim init.vim symlinks
      file:
        src: '{{ ansible_env.HOME }}/dotfiles/init.vim'
        dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
        state: link
        force: yes

    ###############
    # Homebrew Cask
    ###############
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
      tags:
        - cask

    ###################
    # Fish-Shell Setup
    ###################
    - name: fish-shell setup
      become: true
      lineinfile:
        path: /etc/shells
        regexp: '/opt/homebrew/bin/fish'
        insertafter: '/bin/zsh'
        line: '/opt/homebrew/bin/fish'
      tags:
        - fish
    - name: set fish-shell as default
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /opt/homebrew/bin/fish
      tags:
        - fish
    - name: Download fisher plugin manager
      ansible.builtin.get_url:
        url: https://git.io/fisher
        dest: '{{ ansible_env.HOME }}/fisher'
      tags:
        - fish
    - name: Install fisher plugin manager
      ansible.builtin.shell: "source {{ ansible_env.HOME }}/fisher && fisher install jorgebucaran/fisher"
      args:
        executable: /opt/homebrew/bin/fish
        creates: '{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish'
      tags:
        - fish
    - name: Delete fisher installer file
      file:
        dest: '{{ ansible_env.HOME }}/fisher'
        state: absent
      tags:
        - fish
    - name: Install z plugin for fish
      ansible.builtin.shell: "fisher install jethrokuan/z"
      args:
        executable: /opt/homebrew/bin/fish
      tags:
        - fish
    - name: Install peco plugin for fish
      ansible.builtin.shell: "fisher install oh-my-fish/plugin-peco"
      args:
        executable: /opt/homebrew/bin/fish
      tags:
        - fish
    - name: Install bd plugin for fish
      ansible.builtin.shell: "fisher install 0rax/fish-bd"
      args:
        executable: /opt/homebrew/bin/fish
      tags:
        - fish

    # anyenv
    - name: anyenv setting
      file:
        path: '{{ ansible_env.HOME }}/.anyenv/plugins'
        state: directory
      tags:
        - anyenv
    - name: anyenv-update clone
      ansible.builtin.git:
        repo: https://github.com/znz/anyenv-update.git
        dest: '{{ ansible_env.HOME }}/.anyenv/plugins/anyenv-update'
      tags:
        - anyenv

    # java
    - name: java setting
      become: true
      file:
        src: '/opt/homebrew/opt/openjdk/libexec/openjdk.jdk'
        dest: '/Library/Java/JavaVirtualMachines/openjdk.jdk'
        state: link
        force: yes
      tags:
        - java
